import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "NeuroGesture — Communicate with your eyes" }, { name: "description", content: "An assistive communication interface that transforms simple facial and eye gestures into meaningful communication using a standard webcam." }] }),
  component: LandingPage,
});

function Logo(){return <span className="ng-logo"><span>Neuro</span>Gesture</span>}
function LandingPage(){return <div className="ng-page"><header className="ng-header"><Logo/><Link to="/setup" className="primary-btn">Start Communication</Link></header><main className="ng-container" style={{textAlign:"center"}}><section style={{padding:"80px 0 70px"}}><div className="eyebrow">ASSISTIVE COMMUNICATION • WEBCAM • ON-DEVICE</div><h1 style={{fontSize:"clamp(44px,7vw,72px)",maxWidth:900,margin:"18px auto"}}>Communicate with your eyes.</h1><p className="lead" style={{margin:"0 auto",maxWidth:760}}>An assistive communication interface that transforms simple facial and eye gestures into meaningful communication using a standard webcam.</p><Link to="/setup" className="primary-btn" style={{marginTop:30,padding:"16px 28px",fontSize:18}}>START COMMUNICATION</Link></section><section id="how-it-works" style={{padding:"25px 0 80px"}}><h2 style={{fontSize:32,marginBottom:24}}>How it works</h2><div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:10}}>{["Camera","Face Landmarks","Gesture Detection","Menu Navigation","Blink to Select","Voice Output"].map((x,i)=><div key={x} className="info-box" style={{margin:0,padding:"18px 10px",background:i===5?"#e7f6f2":"#fff"}}><strong>{i+1}. {x}</strong></div>)}</div></section><section style={{maxWidth:900,margin:"0 auto 70px",textAlign:"left"}}><div className="info-box"><strong>Built for accessibility</strong><p>Large controls, high readability, keyboard fallback, clear status feedback, and a laptop-first design keep the interface simple to understand and operate.</p></div></section></main><footer style={{borderTop:"1px solid #d7e3e7",padding:"24px",textAlign:"center",color:"#718590"}}>NeuroGesture — student hackathon prototype</footer></div>}
